import Layout from '@/layout/index.vue'

export const constantRoute=[
    {
        path:'/login',
        component:()=>import('@/views/login/index.vue'),
        name:'login',
        meta:{
            title:'登录',
            hidden:true
        }
    },
    //home
    {
        path:'/',
        component:Layout,
        name:'layout',
        redirect: '/home',
        children:[
            {
                path:'/home',
                component:()=>import('@/views/home/index.vue'),
                name:'home',
                meta:{
                    title:'首页',
                    icon:'home'
                }
            }
        ]
    },
    //blog
    {
        path:'/blog',
        component:Layout,
        name:'blog',
        redirect: '/blog/write',
        meta:{
            title:'博客管理',
            icon:'menu'
        },
        children:[
        {
            path:'/blog/write',
            component:()=>import('@/views/blog_controll/blog/writeBlog.vue'),
            name:'writeBlog',
            meta:{
                title:'写博客',
                icon:'write'
            },
        },
        {
            path:'/blog/edit/:id',
            component:()=>import('@/views/blog_controll/blog/writeBlog.vue'),
            name:'editblog',
            meta:{
                title:'编辑文章',
                hidden:true
            },
            props:true
        },
        {
            path:'/blog/blogList',
            component:()=>import('@/views/blog_controll/blog/bolgList.vue'),
            name:'blogList',
            meta:{
                title:'文章管理',
                icon:'article'
            }
        },
        {
            path:'/blog/category',
            component:()=>import('@/views/blog_controll/category/index.vue'),
            name:'category',
            meta:{
                title:'分类管理',
                icon:'category'
            }
        },
        {
            path:'/blog/tag',
            component:()=>import('@/views/blog_controll/tag/index.vue'),
            name:'tag',
            meta:{
                title:'标签管理',
                icon:'tag'
            }
        }

        ]
    },
    //my information
    {
        path:'/myInformation',
        component:Layout,
        name:'My',
        meta:{
            title:'个人信息',
            icon:'person'
        },
        children:[
            {
                path:'/myInformation/about',
                component:()=>import('@/views/my_information/about.vue'),
                name:'About',
                meta:{
                    title:'关于我',
                    icon:'article'
                }
            },
            {
                path:'/myInformation/person',
                component:()=>import('@/views/my_information/person.vue'),
                name:'person',
                meta:{
                    title:'个人设置',
                    icon:'person'
                }
            },
            {
                path:'/myInformation/account',
                component:()=>import('@/views/my_information/account.vue'),
                name:'Account',
                meta:{
                    title:'修改账户',
                    icon:'system'
                }
            }
        ]
    },
    {
        path: '/:pathMatch(.*)*',
        component:()=>import('@/views/404.vue'),
        name:'404',
        meta:{
            title:'404',
            hidden:true
        }
    }
]